version: 0.2
phases:
    pre_build:
        commands:
            - echo PRE_BUILD started
            - aws --version
            - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            - REPOSITORY_URI=590316689173.dkr.ecr.us-west-2.amazonaws.com/ffthh/sisco/wwi-express-svc
    build:
        commands:
            - echo BUILD started
            - docker build -t $REPOSITORY_URI:latest .

    post_build:
        commands:
            - echo POST_BUILD started
            - docker push $REPOSITORY_URI:latest
