version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 10.x
    pre_build:
        commends:
            - yarn install
    build:
        commands:
            - yarn build
            - yarn test