apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwi-express-svc-pods
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
      matchLabels:
        app: wwi-express-svc
  template:
    metadata:
      labels:
        app: wwi-express-svc
    spec:
      containers:
      - image: wwi-express-svc:1.0
        name: wwi-express-svc
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: DB_HOST
          value: "someDatabaseServer.database.windows.net"
        - name: DB_USER
          value: "someUser"
        - name: DB_PASS
          value: "somePass"
        livenessProbe:
          httpGet:
            path: / 
            port: 8081
        resources: 