apiVersion: v1
kind: Service
metadata:
  name: wwi-express-svc-lb
spec:
  type: NodePort
  selector:
    app: wwi-express-svc
  ports:
  - port: 9010
    protocol: TCP
    targetPort: 8081
    nodePort: 30010
